[workspace]
members = ["startup"]

[package]
name = "stm32f429i-disc1"
version = "0.1.0"
edition = "2021"
authors = [""]

[[bin]]
name = "stm32f429i-disc1"
test = false
bench = false

[dependencies]
startup = { path = "startup" }

[profile.release]
codegen-units = 1
debug = true
lto = true

[profile.dev]
debug = true
